Fix nil candidate error
We have seen a few errors via Sentry of `ActionView::Template::Error: undefined method `first_name' for nil:NilClass`, all originating from the RejectedRequestsController.

This controller doesn't use the contact fetcher; it must have been missed when the contact fetcher was originally created.

Update the controller to use the contact fetcher, this should handle missing contact errors where they weren't handled previously.